---
title: Team contract
author: Garret Smith, Daniel Gallagher, Parishi Patel, Ava Byrd
---

# Rationale

Teams work better when members have a common understanding of the team's goals and expectations for collaboration.
The purpose of this activity is to help your team making a plan for working together during lab and outside of the scheduled lab time.
Each team member will have some ideas about how a team should operate.
These ideas may be very different.
This is your opportunity to share your thoughts and ideas to promote optimal team function and prevent misunderstandings in the future.

# Goals

-   What are your team goals for this project?

Our goal is to find an insightful correlation between variables within the data set of our choosing.
We hope to work collaboratively and strengthen our data science skills to discover meaningful outputs.

-   What do you want to accomplish? What skills do you want to develop or refine?

We hope to be able to work with a dataset without structured instructions, and develop the skills to work creatively to discover new features of R.
We hope to refine our skills in data visualization, tidying, and data manipulation whilst incorporating new skills from lecture and outside research.

# Expectations

## Meetings

-   Meeting times: Identify a 1 - 2 hour weekly block outside of lab where the team can meet to work on assignments. All team members should block off this time on their calendar in case the team needs to meet to work on the project. Note: If you are unable to find a weekly time when the team can meet, briefly outline a plan to work on assignments outside of lab.

We plan to meet at 5pm on tuesday.

-   Meeting location: Identify how or where the team will meet to work together (e.g. in-person, Zoom, Facetime, Google Hangouts). Be sure every member is able to access the in-person and/or virtual meeting space.

We will meet on zoom to work together.

## Communication

-   Method of communication: Identify the team's primary method of communication outside of meetings (e.g. GroupMe, Slack, text messages, etc.). Be sure all members are able to access the team's chosen communication platform.

We have created an imessage group chat to communicate.

-   Notifying team members: How should someone notify the other members if they are unable to attend lab or a scheduled team meeting?

They should put it in our group chat.

## Workflow

While it's not productive to divvy up the entire project work at the beginning and bring all the pieces together at the end, there will be times throughout the semester you might decide to divvy up smaller portions of the work among the team members.

-   By when should everyone have their portion of the work completed? *Keep in mind your team will want to have time to review each portion before turning it in to make sure all pieces make sense together and any writing is cohesive.*

Everyone should have their work completed by Sunday at 11:59pm.

-   How should team members communicate if they're struggling with the portion of the work assigned to them?

They can either reach out to the group chat or a member of the team, whichever they are comfortable with.

# Policies & procedures

What rules can you agree on to help you meet your goals and expectations?

We can agree to complete our work on time, communicate when we need help and help each other out when we need help.

# Consequences

How will you address non-performance in regard to these goals, expectations, policies and procedures?

We will communicate and hold each other accountable to ensure that tasks are being accomplished and the agreement is being fulfilled.

# Additional items

Use the remaining space for any other items the team would like to discuss or plan out.

We will make sure we will split up the responsibilities fairly, create a schedule to ensure that tasks are being completed on time and we will have open communication.

------------------------------------------------------------------------

We share these goals and expectations, and agree to these policies, procedures, and consequences.

Team member name: Parishi Patel

Team member name: Garet Smith

Team member name: Daniel Gallagher

Team member name: Ava Byrd

...
